// <auto-generated />
using System;
using LabCMS.EquipmentUsageRecord.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LabCMS.EquipmentUsageRecord.Server.Migrations
{
    [DbContext(typeof(UsageRecordsRepository))]
    partial class UsageRecordsRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", b =>
                {
                    b.Property<string>("EquipmentNo")
                        .HasColumnType("text")
                        .HasColumnName("equipment_no");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment_name");

                    b.Property<string>("HourlyRate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hourly_rate");

                    b.Property<string>("MachineCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_category");

                    b.HasKey("EquipmentNo")
                        .HasName("pk_equipment_hourly_rates");

                    b.ToTable("equipment_hourly_rates");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.Project", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("text")
                        .HasColumnName("no");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("No")
                        .HasName("pk_projects");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_full_name");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.UsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint")
                        .HasColumnName("end_time");

                    b.Property<string>("EquipmentNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipment_no");

                    b.Property<string>("ProjectNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_no");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint")
                        .HasColumnName("start_time");

                    b.Property<string>("TestNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("test_no");

                    b.Property<string>("TestType")
                        .HasColumnType("text")
                        .HasColumnName("test_type");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_usage_records");

                    b.HasIndex("EquipmentNo")
                        .HasDatabaseName("ix_usage_records_equipment_no")
                        .IncludeProperties(new[] { "TestType" });

                    b.HasIndex("ProjectNo")
                        .HasDatabaseName("ix_usage_records_project_no");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_usage_records_start_time");

                    b.ToTable("usage_records");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.UsageRecord", b =>
                {
                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", "EquipmentHourlyRate")
                        .WithMany()
                        .HasForeignKey("EquipmentNo")
                        .HasConstraintName("fk_usage_records_equipment_hourly_rates_equipment_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectNo")
                        .HasConstraintName("fk_usage_records_projects_project_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentHourlyRate");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
