// <auto-generated />
using System;
using LabCMS.EquipmentUsageRecord.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabCMS.EquipmentUsageRecord.Server.Migrations
{
    [DbContext(typeof(UsageRecordsRepository))]
    partial class UsageRecordsRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.ActiveProjectIndex", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("text");

                    b.HasKey("No");

                    b.ToTable("ActiveProjectIndices");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", b =>
                {
                    b.Property<string>("EquipmentNo")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HourlyRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EquipmentNo");

                    b.ToTable("EquipmentHourlyRates");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.Project", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameInFIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("No");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.UsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("EndTime")
                        .HasColumnType("bigint");

                    b.Property<string>("EquipmentNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<string>("TestNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestType")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentNo")
                        .IncludeProperties(new[] { "TestType" });

                    b.HasIndex("ProjectNo");

                    b.HasIndex("StartTime");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.ActiveProjectIndex", b =>
                {
                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.UsageRecord", b =>
                {
                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", "EquipmentHourlyRate")
                        .WithMany()
                        .HasForeignKey("EquipmentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentHourlyRate");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
