// <auto-generated />
using System;
using LabCMS.EquipmentUsageRecord.Server.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LabCMS.EquipmentUsageRecord.Server.Migrations
{
    [DbContext(typeof(UsageRecordsRepository))]
    partial class UsageRecordsRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", b =>
                {
                    b.Property<string>("EquipmentNo")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HourlyRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EquipmentNo");

                    b.ToTable("EquipmentHourlyRates");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.UsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TestNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestType")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentNo")
                        .IncludeProperties(new[] { "TestType" });

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartTime");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.UsageRecord", b =>
                {
                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", "EquipmentHourlyRate")
                        .WithMany("UsageRecords")
                        .HasForeignKey("EquipmentNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabCMS.EquipmentUsageRecord.Shared.Models.Project", "Project")
                        .WithMany("UsageRecords")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentHourlyRate");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.EquipmentHourlyRate", b =>
                {
                    b.Navigation("UsageRecords");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.Shared.Models.Project", b =>
                {
                    b.Navigation("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
