// <auto-generated />
using System;
using LabCMS.EquipmentUsageRecord.MachineDown.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LabCMS.EquipmentUsageRecord.MachineDown.Migrations
{
    [DbContext(typeof(MachineDownRecordsRepository))]
    partial class MachineDownRecordsRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.MachineDown.Models.MachineDownRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MachineDownDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MachineRepairedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MachineDownRecords");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.MachineDown.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LabCMS.EquipmentUsageRecord.MachineDown.Models.MachineDownRecord", b =>
                {
                    b.HasOne("LabCMS.EquipmentUsageRecord.MachineDown.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
